import { Article } from '../types'

const article: Article = {
  id: 'private-credit-banking-banking-relationships',
  title: 'Banking Relationships for Private Credit Funds: Credit Facilities and Cash Management',
  slug: 'banking-relationships',
  subtitle: 'Establishing banking partnerships, structuring subscription lines, and managing fund-level financing for credit portfolios',
  fundType: 'private-credit',
  pillar: 'banking',
  content: `<p>Private credit funds operate at the intersection of lending and investment management, requiring sophisticated banking relationships that support both traditional fund operations and credit-specific financing needs. Unlike private equity funds that primarily deploy capital into equity investments, private credit funds originate, hold, and service loan portfolios, creating unique banking requirements around warehouse facilities, credit lines, fund-level leverage, and specialized cash management systems. The banking infrastructure a credit fund establishes directly impacts its ability to scale originations, manage portfolio risk, optimize capital efficiency, and deliver competitive returns to limited partners.</p>

<h2>Banking Relationship Framework for Credit Funds</h2>

<p>Private credit funds establish multiple banking relationships that serve distinct operational and strategic purposes. The complexity and sophistication of these relationships scale with fund size, strategy, and portfolio characteristics, requiring careful coordination among operating banks, subscription line providers, warehouse facility lenders, and specialized service providers.</p>

<p>Direct lending funds managing between $500 million and $2 billion typically maintain relationships with three to five banking institutions. A primary operating bank handles day-to-day treasury functions, capital call processing, and distribution management. One or two subscription line providers offer credit facilities secured by unfunded limited partner commitments. Warehouse facility lenders provide fund-level leverage against the loan portfolio, enabling capital efficiency and enhanced returns. Specialized banks may provide additional services including foreign exchange execution for international lending, derivatives support for interest rate hedging, or custody services for loan documentation.</p>

<p>Smaller credit funds below $500 million often consolidate relationships to minimize complexity and reduce costs. These funds might work with a single bank that provides both operating accounts and a modest subscription facility, deferring warehouse financing until the portfolio reaches sufficient scale. Larger credit platforms exceeding $2 billion frequently establish syndicated credit facilities involving multiple lenders, diversifying funding sources and accessing larger borrowing capacity than any single institution would provide.</p>

<p>The selection process for banking partners involves evaluating several fund-specific criteria. Experience with credit fund structures proves essential, as lending against loan portfolios requires specialized expertise in collateral valuation, covenant monitoring, and credit risk assessment. Lenders must understand the distinctions between senior secured loans, unitranche facilities, mezzanine debt, and specialty finance assets, applying appropriate advance rates and borrowing base methodologies for each asset type. Banks with dedicated fund finance groups and proven track records in private credit typically offer more competitive terms and smoother ongoing administration.</p>

<p>Geographic considerations influence banking relationships for credit funds with international strategies. A fund originating loans across North America and Europe might establish relationships with U.S. money center banks for dollar-denominated lending and European institutions for euro-denominated activities. This geographic diversification enables local market expertise, reduces foreign exchange costs, and provides operational flexibility for cross-border transactions.</p>

<h2>Subscription Credit Facilities for Private Credit Funds</h2>

<p>Subscription credit facilities, also called capital call facilities or subscription lines, serve as critical liquidity tools for private credit funds, though their utilization patterns differ meaningfully from private equity fund applications. Credit funds deploy subscription lines primarily to bridge timing gaps between loan originations and capital calls, manage portfolio cash flows during interest payment cycles, and fund short-term working capital needs while maintaining efficient capital deployment.</p>

<p>Credit funds structure subscription facilities similarly to private equity funds, with revolving credit agreements secured by unfunded limited partner commitments. The facilities grant lenders security interests in the fund's capital call rights, including direct enforcement mechanisms if the fund defaults on facility obligations. However, several distinctions emerge based on credit fund operational characteristics.</p>

<p>Facility sizing for credit funds typically ranges from 10% to 20% of total limited partner commitments, more conservative than the 15% to 30% common for private equity funds. This reflects the continuous capital deployment nature of credit funds, which originate loans regularly throughout the investment period rather than executing larger, discrete buyout transactions. A $1 billion direct lending fund might establish a $150 million subscription facility (15% of commitments), providing sufficient liquidity for normal origination activity while limiting leverage during the deployment phase.</p>

<p>Credit funds utilize subscription facilities differently than buyout funds. Rather than drawing large amounts to fund individual transactions, credit funds often maintain continuous, moderate borrowing levels that fluctuate based on origination pipelines and capital call timing. A fund might maintain $30 million to $50 million drawn continuously, calling capital quarterly to repay the facility and reset borrowing capacity. This usage pattern creates more consistent interest expense compared to the lumpy borrowing patterns typical in private equity.</p>

<p>Subscription facility documentation for credit funds includes specific provisions addressing credit portfolio risks. Lenders often require representations regarding the fund's compliance with its investment guidelines, portfolio concentration limits, and asset quality metrics. Some facilities include provisions restricting draws if the loan portfolio deteriorates below specified credit quality thresholds, such as weighted average ratings, default rates, or non-performing asset levels. A facility might prohibit incremental borrowing if more than 5% of the loan portfolio by value becomes non-performing.</p>

<p>Pricing for credit fund subscription facilities generally aligns with private equity fund terms, with interest rates based on SOFR plus spreads ranging from 150 to 300 basis points depending on fund profile and LP creditworthiness. However, credit funds may negotiate slightly higher spreads due to perceived correlation risk between the fund's credit portfolio and economic conditions that might stress limited partner ability to fund capital calls. Established credit managers with institutional LP bases command tighter pricing, while first-time managers pay premium spreads reflecting execution risk and less established investor relationships.</p>

<p>Covenant structures in credit fund subscription facilities typically mirror private equity fund provisions, with borrowing base calculations limiting draws to percentages of unfunded commitments from eligible limited partners. Lenders exclude commitments from LPs with credit concerns, insufficient financial capacity, or problematic jurisdictions. A facility might establish tiered advance rates based on LP credit quality, allowing 100% borrowing against commitments from highly rated institutions while limiting borrowing to 50% or 75% against commitments from family offices or lower-rated investors.</p>

<h2>Warehouse Facilities and Fund-Level Financing</h2>

<p>Warehouse facilities represent the most distinctive banking relationship for private credit funds, providing secured credit lines collateralized by the fund's loan portfolio. These facilities enable credit funds to employ moderate leverage, typically ranging from 1.25x to 2.0x debt-to-equity, enhancing returns to limited partners while maintaining prudent risk management. Unlike subscription lines that provide temporary working capital, warehouse facilities function as semi-permanent capital structures that remain in place throughout the fund's life.</p>

<p>Warehouse facility structures involve secured lending agreements where the credit fund pledges its loan portfolio as collateral. The lender advances funds based on a borrowing base calculation that applies advance rates to eligible loan assets. A direct lending fund holding senior secured loans might receive 60% to 75% advance rates on performing assets, meaning a $100 million portfolio could support $60 million to $75 million of warehouse borrowing. Advance rates vary significantly based on loan seniority, credit quality, industry concentration, and documentation standards.</p>

<p>Borrowing base mechanics require sophisticated portfolio monitoring and ongoing compliance. The warehouse agreement defines eligible collateral criteria, typically limiting advances to senior secured loans, excluding equity holdings and deeply subordinated debt, imposing concentration limits by borrower, industry, and geography, requiring minimum portfolio diversity (often 15 to 25 distinct obligors), and establishing credit quality thresholds based on internal ratings or external assessments. Funds must provide regular borrowing base certificates, usually monthly, demonstrating continued compliance with collateral eligibility criteria.</p>

<p>As loans move in and out of the portfolio through originations, repayments, and credit deterioration, the borrowing base fluctuates dynamically. Strong credit performance and regular originations of high-quality loans increase borrowing capacity, while credit deterioration, loan repayments, or portfolio concentration can reduce available capacity. Fund managers must monitor borrowing base availability carefully, maintaining sufficient cushion above actual borrowing levels to accommodate normal fluctuations without triggering margin calls or forced deleveraging.</p>

<p>Warehouse facility covenants extend beyond borrowing base requirements to include portfolio performance metrics. Common covenants include maximum weighted average default rates (often 2% to 4% of portfolio value), minimum weighted average credit ratings, limitations on non-performing or workout loans as a percentage of total portfolio, and restrictions on portfolio concentration to specific industries or borrowers. These covenants ensure that warehouse lenders maintain security interests in portfolios of appropriate credit quality, triggering events of default if credit performance deteriorates materially.</p>

<p>Pricing for warehouse facilities reflects the secured nature of the lending and the credit quality of underlying collateral. Interest rates typically range from SOFR plus 200 to 400 basis points, with tighter spreads for facilities secured by high-quality senior secured loans and wider spreads for subordinated debt or specialty finance portfolios. Facilities also include unused commitment fees of 50 to 100 basis points annually on undrawn capacity. Large credit funds with diversified portfolios of performing senior loans negotiate favorable terms, while smaller or more concentrated portfolios pay premium pricing reflecting higher perceived risk.</p>

<p>Fund managers must carefully consider the economic impact of warehouse facilities on fund returns. While leverage enhances equity returns during strong credit performance, it amplifies losses during stress periods. A fund earning 10% gross returns on unlevered investments might enhance equity returns to 14% to 16% with 1.5x leverage, but the same leverage would amplify losses during credit deterioration. Limited partnership agreements typically restrict maximum fund-level leverage, often capping debt at 1.5x to 2.0x NAV, ensuring managers maintain conservative leverage profiles aligned with investor expectations.</p>

<h2>Cash Management for Credit Fund Portfolios</h2>

<p>Cash management in private credit funds involves complexities beyond traditional private equity treasury operations. Credit funds receive continuous cash inflows from loan interest payments, principal amortization, and prepayments while managing outflows for new originations, operating expenses, and distributions to limited partners. This continuous cash cycling requires sophisticated systems for tracking, forecasting, and optimizing cash positions.</p>

<p>Interest collection represents the primary recurring cash inflow for credit funds. Most middle market loans pay quarterly interest, creating predictable collection patterns that fund managers must track carefully. Funds typically establish detailed interest payment tracking systems that monitor expected payment dates, flag late payments within cure periods, and escalate non-payments to portfolio management teams. Automated systems reconcile incoming wire transfers against expected interest amounts, identifying discrepancies that might indicate borrower stress or payment processing errors.</p>

<p>Principal repayments, whether scheduled amortization or voluntary prepayments, create lumpy cash inflows that impact capital deployment planning. Credit fund managers must maintain sophisticated portfolio cash flow models that project expected amortization schedules, estimate prepayment probabilities based on historical patterns and market conditions, and plan capital recycling strategies. A fund approaching the end of its investment period might use principal repayments to repay warehouse facilities and prepare for liquidation, while a fund in active deployment would typically recycle repayments into new originations.</p>

<p>Cash management efficiency directly impacts fund returns through several mechanisms. Maintaining excess cash balances reduces effective deployment rates and dilutes returns, while inadequate cash reserves can force funds to miss attractive origination opportunities or delay distributions to limited partners. Credit funds typically target cash balances equal to 30 to 90 days of expected expenses plus a buffer for near-term origination commitments, though optimal levels vary based on pipeline visibility and portfolio maturity.</p>

<p>Limited partnership agreements typically restrict how credit funds invest uninvested cash, similar to private equity fund provisions. These restrictions ensure liquidity and prevent inappropriate risk-taking with capital committed for credit investments. Common permitted investments include bank deposits, money market funds, Treasury securities, investment-grade commercial paper, and other short-term liquid instruments with maturity restrictions of 90 to 180 days. Some agreements permit investment in short-duration bond funds or stable value funds, providing modestly higher yields while maintaining daily liquidity.</p>

<p>Large credit funds with consistently substantial cash balances establish automated sweep arrangements that optimize interest income. These systems maintain target operating balances for daily treasury needs while automatically investing excess cash in money market funds or other permitted instruments. A fund might maintain $5 million to $10 million in its operating account for ordinary course activities, sweeping excess balances nightly into money market accounts earning 25 to 50 basis points of additional yield. Over time, these incremental returns compound meaningfully on cash balances that might average $50 million to $100 million during deployment phases.</p>

<h2>Credit Facility Management and Covenant Compliance</h2>

<p>Managing multiple credit facilities simultaneously—subscription lines, warehouse facilities, and potentially revolving credit agreements—requires disciplined processes for monitoring borrowing levels, tracking covenant compliance, and coordinating among lenders. Credit fund treasury teams establish comprehensive dashboards that provide real-time visibility into facility utilization, available capacity, and covenant metrics.</p>

<p>Subscription line management focuses on optimizing the timing of draws and repayments to minimize interest expense while maintaining adequate liquidity. Funds typically draw on subscription lines as needed for originations, maintaining borrowings for 30 to 90 days before issuing capital calls to repay the facility. This batching approach reduces capital call frequency, improving LP satisfaction while managing interest costs. Some funds maintain modest continuous subscription line borrowings, optimizing the timing of capital calls to quarterly or semi-annual cycles that align with interest payment collections from the portfolio.</p>

<p>Warehouse facility management demands continuous attention to borrowing base dynamics and collateral quality. Treasury teams work closely with portfolio management to track loans approaching maturity, monitor credit deterioration that might impact collateral eligibility, and plan new originations that increase borrowing capacity. Monthly borrowing base certificate preparation requires detailed portfolio analysis, with teams verifying that each loan meets eligibility criteria, calculating correct advance rates based on current loan classifications, and ensuring concentration limits remain satisfied.</p>

<p>Covenant compliance reporting requires coordination among fund controllers, portfolio managers, and treasury teams. Facilities typically require monthly or quarterly compliance certificates demonstrating adherence to financial covenants, borrowing base requirements, and operational restrictions. These certificates include detailed calculations of covenant metrics, such as weighted average default rates, portfolio concentration statistics, and leverage ratios. Material covenant violations can trigger events of default, requiring immediate remediation and potentially accelerating facility repayment obligations.</p>

<p>Proactive covenant management involves maintaining sufficient cushion above compliance thresholds to absorb normal portfolio fluctuations. Credit fund managers typically establish internal monitoring levels more conservative than covenant requirements, triggering management attention and potential remedial action before actual violations occur. A facility with a 4% maximum default rate covenant might establish an internal 3% monitoring threshold, escalating portfolio concerns when defaults approach that level rather than waiting until covenant violations become imminent.</p>

<h2>Foreign Exchange Management for International Credit Strategies</h2>

<p>Credit funds originating loans in multiple currencies face foreign exchange exposure management challenges that require specialized banking relationships and hedging strategies. Unlike private equity funds that typically accept currency risk as part of equity returns, credit funds with non-dollar lending often implement hedging programs to protect predictable interest income streams from exchange rate volatility.</p>

<p>The nature of credit investments creates distinct FX management considerations. Loan agreements specify contractual interest rates and repayment terms in the origination currency, creating predictable cash flows that lend themselves to hedging. A fund originating a five-year euro-denominated loan at 8% interest can reasonably forecast quarterly interest payments, enabling forward currency contracts or cross-currency swaps that lock in dollar-equivalent returns for limited partners.</p>

<p>Many credit funds establish currency hedging policies within their limited partnership agreements, defining acceptable hedging instruments, strategy parameters, and board oversight requirements. Common approaches include passive hedging that attempts to neutralize currency exposure through forward contracts matched to expected interest collections, liability-based hedging that uses euro-denominated warehouse borrowings to offset euro-denominated loan assets, or selective hedging that protects currencies exhibiting significant volatility while accepting modest exposure in stable currency pairs.</p>

<p>Implementing hedging programs requires banking relationships with institutions offering comprehensive foreign exchange and derivatives capabilities. Funds establish International Swaps and Derivatives Association (ISDA) agreements with counterparties, defining legal frameworks for derivative transactions. Banks provide forward currency contracts, cross-currency swaps, and currency options, with pricing reflecting prevailing interest rate differentials, contract duration, and counterparty credit assessment. Large credit funds with substantial multi-currency exposure often negotiate competitive pricing through master ISDA agreements covering all anticipated derivative activities.</p>

<p>Currency hedging creates operational complexity and cost that must be weighed against risk reduction benefits. Forward contracts require margin posting as exchange rates move, creating working capital demands. Hedging costs, reflected in forward points or swap spreads, reduce net returns to limited partners. Many credit funds conclude that hedging costs for stable currency pairs like EUR/USD or GBP/USD outweigh benefits for long-duration investments, instead accepting currency exposure as part of the investment program. However, funds with lending in emerging market currencies or currencies with higher volatility often implement hedging to protect against material FX-driven performance impacts.</p>

<h2>Banking KYC/AML for Credit Fund Operations</h2>

<p>Private credit funds face extensive know-your-customer and anti-money laundering requirements when establishing banking relationships, driven by regulatory frameworks including the Bank Secrecy Act, USA PATRIOT Act, and international equivalents. These requirements intensify for credit funds relative to private equity funds due to the continuous transaction activity inherent in lending operations.</p>

<p>Account opening procedures require comprehensive documentation packages including the fund's limited partnership agreement and amendments, certificates of formation for the fund and general partner entities, detailed organizational charts showing ownership structures, lists of authorized signatories with delegation documentation, beneficial ownership information identifying individuals with 25% or more ownership of the general partner, and extensive information about the fund's investment strategy, target borrower profiles, and expected transaction patterns. Credit funds must also provide sample loan documents, underwriting criteria, and credit policies, enabling banks to understand the fund's lending activities and establish appropriate monitoring frameworks.</p>

<p>Beneficial ownership requirements create particular complexity for credit funds with institutional limited partners. Banks must identify and verify natural persons who ultimately own or control the fund, requiring analysis through potentially multiple entity layers. For funds with pension plans, endowments, or sovereign wealth funds as investors, banks typically accept reasonable verification procedures identifying controlling persons at the institutional level rather than attempting to trace through to individual beneficiaries. Nevertheless, this verification process requires extensive documentation and can delay account opening by weeks or months.</p>

<p>Ongoing monitoring obligations require credit funds to report material changes in strategy, LP composition, or operations. Banks conduct periodic reviews requesting updated documentation and explanations for transaction patterns that deviate from expected activity. Credit funds experience more frequent reviews than private equity funds due to higher transaction volumes and the need for banks to understand loan origination activities. A fund might receive quarterly requests to explain new lending jurisdictions, unusual borrower profiles, or transaction structures that differ from historical patterns.</p>

<p>Transaction monitoring systems flag potentially suspicious activity for enhanced review. Credit funds making dozens or hundreds of loan fundings annually trigger more frequent inquiries than equity funds making a handful of investments per year. Fund managers must maintain detailed transaction support, including loan documentation, borrower background information, and business purpose explanations, to respond efficiently to bank inquiries. Establishing clear communication channels with bank compliance teams and providing proactive updates about anticipated transaction patterns helps minimize disruptions from routine monitoring activities.</p>

<h2>Account Structure and Operational Framework</h2>

<p>Credit funds establish more complex account structures than private equity funds, reflecting the continuous cash flow activity associated with lending operations. The account architecture must support loan fundings, interest and principal collections, facility draws and repayments, capital calls, expense payments, and LP distributions while maintaining clear audit trails and appropriate segregation.</p>

<p>Primary operating accounts serve as the central treasury hubs for day-to-day cash management. Credit funds typically maintain these accounts at their primary banking relationship, using them to receive interest payments from borrowers, process loan fundings, pay operating expenses, and coordinate capital calls and distributions. Large credit funds with multi-currency strategies maintain separate operating accounts for each currency, minimizing foreign exchange conversion costs and simplifying cash management for international lending activities.</p>

<p>Subscription facility accounts operate under lender control arrangements, with funds maintaining segregated accounts specifically for subscription line draws and repayments. When funds draw on subscription lines, proceeds flow into these designated accounts. The subscription lender maintains security interests and control rights over the accounts, restricting transfers except as permitted under facility documentation. This control structure ensures that capital called to repay subscription line borrowings actually reaches the lender rather than being diverted to other uses.</p>

<p>Warehouse facility accounts function similarly, with dedicated accounts for facility draws and, importantly, for collecting loan payments that secure the facility. Many warehouse facilities require that borrowers make interest and principal payments directly into controlled accounts pledged to the warehouse lender. The lender monitors these collection accounts, applying receipts to reduce facility balances or releasing funds to the fund based on agreement terms. This payment waterfall structure protects warehouse lenders by ensuring they receive priority application of portfolio cash flows.</p>

<p>Distribution accounts serve as temporary holding accounts when funds make distributions to limited partners. Some funds establish these accounts to create clear segregation between operating activities and investor distributions, simplifying accounting and audit procedures. The practice becomes particularly valuable for funds with complex waterfall provisions or multiple share classes requiring different distribution calculations.</p>

<p>Expense accounts maintained by some larger credit funds segregate ordinary course operating expenses from investment-related cash flows. This segregation simplifies expense tracking against management fee budgets and creates cleaner accounting separation between fund operations and portfolio activities. Smaller funds typically manage all expenses through primary operating accounts, finding that additional account complexity outweighs organizational benefits.</p>

<h2>Treasury Operations and Payment Processing</h2>

<p>Treasury operations in credit funds encompass daily management of cash positions, loan funding execution, interest collection processing, facility management, and distribution preparation. The operational intensity scales with portfolio size and lending activity, with large credit funds maintaining dedicated treasury teams while smaller funds combine treasury responsibilities within broader finance functions.</p>

<p>Loan funding procedures require careful coordination among origination teams, legal counsel, and treasury functions. For each new loan, treasury teams verify that all closing conditions have been satisfied, coordinate timing with borrowers and any syndicate partners, execute outgoing wire transfers on closing dates, and update facility borrowing base certificates to reflect new collateral. Many credit funds establish dual-control procedures requiring multiple authorized signatories for outgoing wires above specified thresholds, typically $1 million to $5 million, reducing fraud risk and ensuring appropriate oversight of material disbursements.</p>

<p>Interest collection processing demands systematic tracking of expected payments and rigorous follow-up procedures. Treasury teams maintain detailed payment calendars showing scheduled interest dates for each loan, monitor accounts for incoming wire transfers, reconcile receipts against expected amounts within 24 to 48 hours, and escalate late payments to portfolio management teams. Automated systems increasingly handle much of this processing, automatically matching incoming wires to expected payments and flagging discrepancies for human review. However, given the materiality of interest income to fund returns, human oversight remains critical for identifying payment issues that might indicate borrower stress.</p>

<p>Capital call processing for credit funds follows similar procedures to private equity funds, with treasury teams calculating call amounts based on funding needs, preparing capital call notices with appropriate advance notice periods, tracking incoming LP wires, following up on late payments, and applying default provisions when necessary. However, credit funds typically execute capital calls more frequently than buyout funds, often quarterly or even monthly during active deployment, requiring efficient processing systems that minimize administrative burden.</p>

<p>Distribution processing involves calculating LP entitlements based on fund waterfall provisions, preparing distribution notices, executing wires to limited partners, and providing appropriate tax documentation. Credit funds making regular distributions from interest income establish recurring procedures, often distributing quarterly based on collected interest net of expenses and facility interest costs. The frequency and predictability of credit fund distributions create investor relations benefits, though funds must balance distribution frequency against administrative costs and tax efficiency considerations.</p>

<h2>Key Takeaways</h2>

<ul>
<li>Private credit funds require more complex banking relationships than private equity funds, establishing multiple partnerships for operating accounts, subscription lines, warehouse facilities, and specialized services like foreign exchange and derivatives support</li>
<li>Subscription facilities for credit funds typically range from 10% to 20% of commitments, providing working capital for continuous origination activities with usage patterns characterized by moderate, sustained borrowing rather than large, discrete draws</li>
<li>Warehouse facilities secured by loan portfolios enable fund-level leverage of 1.25x to 2.0x, applying advance rates of 60% to 75% on senior secured loans while imposing borrowing base requirements and portfolio quality covenants</li>
<li>Cash management in credit funds involves tracking continuous interest collections, principal repayments, and prepayments while maintaining optimal cash balances that balance deployment efficiency against operational liquidity needs</li>
<li>Credit facility management requires disciplined monitoring of borrowing base dynamics, covenant compliance, and collateral eligibility, with treasury teams maintaining sufficient cushion above covenant thresholds to absorb portfolio fluctuations</li>
<li>Foreign exchange management for multi-currency credit strategies involves decisions about hedging predictable interest income streams, balancing risk reduction benefits against hedging costs and operational complexity</li>
<li>Enhanced KYC/AML requirements reflect the transaction intensity of credit operations, requiring comprehensive documentation at account opening and ongoing monitoring of lending activities, borrower profiles, and transaction patterns</li>
<li>Account structures for credit funds include segregated accounts for operations, subscription facilities, warehouse facilities, loan collections, and distributions, creating appropriate audit trails and meeting lender control requirements</li>
</ul>`,
  metaTitle: 'Banking Relationships for Private Credit Funds: Credit Facilities and Cash Management',
  metaDescription: 'Comprehensive guide to private credit fund banking: subscription lines, warehouse facilities, fund-level leverage, cash management, and credit facility operations.',
  publishedDate: 'December 18, 2024',
  readingTime: 14,
}

export default article
