/**
 * Curated domain map for well-known firms in the fund industry.
 *
 * Keys are lowercase firm names (and common variations).
 * Values are the correct website domain used to fetch favicons.
 *
 * The FirmLogo component checks this map first, then falls back to
 * the domain from the classification pipeline, then to a letter initial.
 */
export const FIRM_DOMAIN_MAP: Record<string, string> = {
  // ── Mega / Large-cap PE ─────────────────────────────────────────────
  'apollo': 'apollo.com',
  'apollo global management': 'apollo.com',
  'apollo global management, inc.': 'apollo.com',
  'blackstone': 'blackstone.com',
  'blackstone group': 'blackstone.com',
  'kkr': 'kkr.com',
  'kkr & co': 'kkr.com',
  'carlyle': 'carlyle.com',
  'carlyle group': 'carlyle.com',
  'the carlyle group': 'carlyle.com',
  'tpg': 'tpg.com',
  'tpg capital': 'tpg.com',
  'warburg pincus': 'warburgpincus.com',
  'bain capital': 'baincapital.com',
  'eqt': 'eqtgroup.com',
  'eqt partners': 'eqtgroup.com',
  'thoma bravo': 'thomabravo.com',
  'vista equity partners': 'vistaequitypartners.com',
  'vista equity': 'vistaequitypartners.com',
  'advent international': 'adventinternational.com',
  'advent': 'adventinternational.com',
  'hellman & friedman': 'hfriedman.com',
  'silver lake': 'silverlake.com',
  'silver lake partners': 'silverlake.com',
  'permira': 'permira.com',
  'cvc capital partners': 'cvc.com',
  'cvc': 'cvc.com',
  'cinven': 'cinven.com',
  'apax partners': 'apax.com',
  'apax': 'apax.com',
  'general atlantic': 'generalatlantic.com',
  'leonard green & partners': 'leonardgreen.com',
  'leonard green': 'leonardgreen.com',
  'gtcr': 'gtcr.com',
  'madison dearborn partners': 'mdcp.com',
  'madison dearborn': 'mdcp.com',
  'welsh carson': 'welshcarson.com',
  'welsh, carson, anderson & stowe': 'welshcarson.com',

  // ── Large PE (continued) ────────────────────────────────────────────
  'bc partners': 'bcpartners.com',
  'pai partners': 'paipartners.com',
  'pai': 'paipartners.com',
  'nordic capital': 'nordiccapital.com',
  'investcorp': 'investcorp.com',
  'sun capital': 'suncappart.com',
  'sun capital partners': 'suncappart.com',
  'francisco partners': 'franciscopartners.com',
  'cd&r': 'cdr-inc.com',
  'clayton dubilier & rice': 'cdr-inc.com',
  'clayton dubilier': 'cdr-inc.com',
  'providence equity': 'provequity.com',
  'providence equity partners': 'provequity.com',
  'cerberus': 'cerberus.com',
  'cerberus capital management': 'cerberus.com',
  'lone star': 'lonestarfunds.com',
  'lone star funds': 'lonestarfunds.com',
  'l catterton': 'lcatterton.com',
  'catterton': 'lcatterton.com',
  'eurazeo': 'eurazeo.com',
  'wendel': 'wendelgroup.com',
  '3i': '3i.com',
  '3i group': '3i.com',
  'montagu private equity': 'montagu.com',
  'montagu': 'montagu.com',

  // ── Mid-market PE ───────────────────────────────────────────────────
  'charlesbank': 'charlesbank.com',
  'charlesbank capital partners': 'charlesbank.com',
  'oakley capital': 'oakleycapital.com',
  'triton partners': 'triton-partners.com',
  'triton': 'triton-partners.com',
  'norvestor': 'norvestor.com',
  'audax': 'audaxprivateequity.com',
  'audax private equity': 'audaxprivateequity.com',
  'kinderhook industries': 'kinderhook.com',
  'accel-kkr': 'accel-kkr.com',
  'genstar capital': 'genstarcapital.com',
  'genstar': 'genstarcapital.com',
  'hig capital': 'higcapital.com',
  'h.i.g. capital': 'higcapital.com',
  'platinum equity': 'platinumequity.com',
  'clearlake capital': 'clearlake.com',
  'clearlake capital group': 'clearlake.com',
  'clearlake': 'clearlake.com',
  'insight partners': 'insightpartners.com',
  'insight': 'insightpartners.com',
  'veritas capital': 'veritascapital.com',
  'veritas': 'veritascapital.com',
  'roark capital': 'roarkcapital.com',
  'roark': 'roarkcapital.com',
  'new mountain capital': 'newmountaincapital.com',
  'new mountain': 'newmountaincapital.com',
  'berkshire partners': 'berkshirepartners.com',
  'berkshire': 'berkshirepartners.com',
  'summit partners': 'summitpartners.com',
  'summit': 'summitpartners.com',
  'ta associates': 'ta.com',
  'bridgepoint': 'bridgepoint.eu',
  'hg capital': 'hgcapital.com',
  'hg': 'hgcapital.com',
  'american securities': 'americansecurities.com',
  'kelso': 'kelso.com',
  'kelso & company': 'kelso.com',
  'sentinel capital': 'sentinelpartners.com',
  'sentinel capital partners': 'sentinelpartners.com',
  'crestview partners': 'crestview.com',
  'crestview': 'crestview.com',
  'searchlight capital': 'searchlightcap.com',
  'searchlight capital partners': 'searchlightcap.com',
  'towerbrook': 'towerbrook.com',
  'towerbrook capital': 'towerbrook.com',
  'mbk partners': 'mbkpartnerslp.com',
  'pag': 'pag.com',
  'chryscapital': 'chryscapital.com',
  'sofinnova': 'sofinnova.com',
  'sofinnova partners': 'sofinnova.com',
  'cathay capital': 'cathaycapital.com',
  'arcmont': 'arcmont.com',
  'arcmont asset management': 'arcmont.com',
  'verdane': 'verdane.com',
  'verdane capital': 'verdane.com',

  // ── Credit / Alternatives ───────────────────────────────────────────
  'ares': 'aresmgmt.com',
  'ares management': 'aresmgmt.com',
  'ares capital': 'aresmgmt.com',
  'oaktree': 'oaktreecapital.com',
  'oaktree capital': 'oaktreecapital.com',
  'oaktree capital management': 'oaktreecapital.com',
  'blue owl': 'blueowl.com',
  'blue owl capital': 'blueowl.com',
  'fortress': 'fortress.com',
  'fortress investment group': 'fortress.com',
  'benefit street partners': 'benefitstreetpartners.com',
  'golub capital': 'golubcapital.com',
  'golub': 'golubcapital.com',
  'owl rock': 'blueowl.com',
  'owl rock capital': 'blueowl.com',
  'sixth street': 'sixthstreet.com',
  'sixth street partners': 'sixthstreet.com',
  'hps investment partners': 'hpspartners.com',
  'hps': 'hpspartners.com',
  'antares capital': 'antares.com',
  'antares': 'antares.com',
  'churchill asset management': 'churchillam.com',
  'varagon capital': 'varagoncapital.com',
  'prospect capital': 'prospectcapital.com',
  'main street capital': 'mainstcapital.com',
  'crescent capital': 'crescentcap.com',
  'crescent capital group': 'crescentcap.com',
  'tcw': 'tcw.com',
  'tcw group': 'tcw.com',
  'angelo gordon': 'angelogordon.com',
  'atalaya capital': 'atalayacap.com',
  'atalaya': 'atalayacap.com',
  'barings': 'barings.com',
  'midcap financial': 'midcapfinancial.com',
  'pimco': 'pimco.com',
  'pgim private capital': 'pgim.com',
  'nuveen private capital': 'nuveen.com',
  'owl rock technology finance': 'blueowl.com',
  'kayne anderson': 'kayneanderson.com',
  'kayne anderson capital advisors': 'kayneanderson.com',

  // ── Hedge Funds ─────────────────────────────────────────────────────
  'saba capital': 'sabacapital.com',
  'saba capital management': 'sabacapital.com',
  'elliott': 'elliottinv.com',
  'elliott investment management': 'elliottinv.com',
  'elliott management': 'elliottinv.com',
  'trian fund management': 'trianpartners.com',
  'trian': 'trianpartners.com',
  'davidson kempner': 'davidsonkempner.com',
  'davidson kempner capital management': 'davidsonkempner.com',
  'bridgewater': 'bridgewater.com',
  'bridgewater associates': 'bridgewater.com',
  'citadel': 'citadel.com',
  'citadel llc': 'citadel.com',
  'two sigma': 'twosigma.com',
  'two sigma investments': 'twosigma.com',
  'de shaw': 'deshaw.com',
  'd.e. shaw': 'deshaw.com',
  'millennium': 'mlp.com',
  'millennium management': 'mlp.com',
  'man group': 'man.com',
  'man glg': 'man.com',
  'man ahl': 'man.com',
  'point72': 'point72.com',
  'point72 asset management': 'point72.com',
  'aqr': 'aqr.com',
  'aqr capital management': 'aqr.com',
  'balyasny': 'balyasny.com',
  'balyasny asset management': 'balyasny.com',
  'baupost': 'baupost.com',
  'baupost group': 'baupost.com',
  'brevan howard': 'brevanhoward.com',
  'capula': 'capula.com',
  'capula investment management': 'capula.com',
  'coatue': 'coatue.com',
  'coatue management': 'coatue.com',
  'd1 capital': 'd1cap.com',
  'd1 capital partners': 'd1cap.com',
  'farallon': 'faralloncapital.com',
  'farallon capital': 'faralloncapital.com',
  'jane street': 'janestreet.com',
  'marshall wace': 'mwam.com',
  'magnetar': 'magnetarcapital.com',
  'magnetar capital': 'magnetarcapital.com',
  'moore capital': 'moorecap.com',
  'sculptor': 'sculptor.com',
  'sculptor capital': 'sculptor.com',
  'renaissance technologies': 'rentec.com',
  'rentec': 'rentec.com',
  'rokos': 'rokoscapital.com',
  'rokos capital': 'rokoscapital.com',
  'schonfeld': 'schonfeld.com',
  'schonfeld strategic advisors': 'schonfeld.com',
  'third point': 'thirdpoint.com',
  'third point llc': 'thirdpoint.com',
  'tiger global': 'tigerglobal.com',
  'tiger global management': 'tigerglobal.com',
  'tudor': 'tudorfunds.com',
  'tudor investment corp': 'tudorfunds.com',
  'viking global': 'vikingglobal.com',
  'viking global investors': 'vikingglobal.com',
  'winton': 'winton.com',
  'winton group': 'winton.com',
  'exoduspoint': 'exoduspoint.com',
  'exoduspoint capital': 'exoduspoint.com',
  'pershing square': 'pershingsquareholdings.com',
  'pershing square capital': 'pershingsquareholdings.com',
  'valueact': 'valueact.com',
  'valueact capital': 'valueact.com',
  'icahn enterprises': 'icahnenterprises.com',
  'carl icahn': 'icahnenterprises.com',
  'hudson bay capital': 'hudsonbaycapital.com',
  'hudson bay': 'hudsonbaycapital.com',
  'eisler capital': 'eislercapital.com',
  'eisler': 'eislercapital.com',

  // ── Real Estate ─────────────────────────────────────────────────────
  'prologis': 'prologis.com',
  'brookfield': 'brookfield.com',
  'brookfield asset management': 'brookfield.com',
  'brookfield infrastructure': 'brookfield.com',
  'brookfield renewable': 'brookfield.com',
  'starwood capital': 'starwoodcapital.com',
  'starwood capital group': 'starwoodcapital.com',
  'starwood': 'starwoodcapital.com',
  'gaw capital': 'gawcapital.com',
  'cbre': 'cbre.com',
  'cbre group': 'cbre.com',
  'jll': 'jll.com',
  'jones lang lasalle': 'jll.com',
  'hines': 'hines.com',
  'greystar': 'greystar.com',
  'greystar real estate': 'greystar.com',
  'tishman speyer': 'tishmanspeyer.com',
  'related companies': 'related.com',
  'related': 'related.com',
  'digitalbridge': 'digitalbridge.com',
  'heitman': 'heitman.com',
  'lendlease': 'lendlease.com',
  'oxford properties': 'oxfordproperties.com',
  'patrizia': 'patrizia.ag',
  'patrizia se': 'patrizia.ag',
  'rockpoint': 'rockpointgroup.com',
  'rockpoint group': 'rockpointgroup.com',
  'harrison street': 'harrisonst.com',
  'harrison street real estate': 'harrisonst.com',
  'aew': 'aew.com',
  'aew capital management': 'aew.com',
  'cushman & wakefield': 'cushmanwakefield.com',
  'colliers': 'colliers.com',
  'colliers international': 'colliers.com',
  'marcus & millichap': 'marcusmillichap.com',
  'eastdil secured': 'eastdilsecured.com',

  // ── VC ──────────────────────────────────────────────────────────────
  'partech': 'partechpartners.com',
  'partech partners': 'partechpartners.com',
  'sequoia': 'sequoiacap.com',
  'sequoia capital': 'sequoiacap.com',
  'a16z': 'a16z.com',
  'andreessen horowitz': 'a16z.com',
  'accel': 'accel.com',
  'accel partners': 'accel.com',
  'benchmark': 'benchmark.com',
  'benchmark capital': 'benchmark.com',
  'greylock': 'greylock.com',
  'greylock partners': 'greylock.com',
  'lightspeed': 'lsvp.com',
  'lightspeed venture partners': 'lsvp.com',
  'general catalyst': 'generalcatalyst.com',
  'index ventures': 'indexventures.com',
  'founders fund': 'foundersfund.com',
  'bessemer': 'bvp.com',
  'bessemer venture partners': 'bvp.com',
  'breakout ventures': 'breakout.vc',
  'khosla ventures': 'khoslaventures.com',
  'khosla': 'khoslaventures.com',
  'kleiner perkins': 'kleinerperkins.com',
  'nea': 'nea.com',
  'new enterprise associates': 'nea.com',
  'battery ventures': 'battery.com',
  'battery': 'battery.com',
  'canaan': 'canaan.com',
  'canaan partners': 'canaan.com',
  'ggv capital': 'ggvc.com',
  'ggv': 'ggvc.com',
  'gv': 'gv.com',
  'google ventures': 'gv.com',
  'ivp': 'ivp.com',
  'institutional venture partners': 'ivp.com',
  'menlo ventures': 'menlovc.com',
  'norwest venture partners': 'nvp.com',
  'norwest': 'nvp.com',
  'ribbit capital': 'ribbitcap.com',
  'ribbit': 'ribbitcap.com',
  'sapphire ventures': 'sapphireventures.com',
  'scale venture partners': 'scalevp.com',
  'union square ventures': 'usv.com',
  'y combinator': 'ycombinator.com',
  'yc': 'ycombinator.com',
  'softbank': 'softbank.com',
  'softbank vision fund': 'softbank.com',
  'redpoint ventures': 'redpoint.com',
  'redpoint': 'redpoint.com',
  'balderton capital': 'balderton.com',
  'balderton': 'balderton.com',
  'atomico': 'atomico.com',
  'lux capital': 'luxcapital.com',
  'lux': 'luxcapital.com',
  'arch venture partners': 'archventure.com',
  'arch ventures': 'archventure.com',
  'orbimed': 'orbimed.com',
  'orbimed advisors': 'orbimed.com',
  '8vc': '8vc.com',
  '500 global': '500.co',
  'elevation capital': 'elevationcapital.com',
  'cathay innovation': 'cathayinnovation.com',
  'third rock ventures': 'thirdrockventures.com',

  // ── Asset Managers / Banks / Multi-strategy ─────────────────────────
  'blackrock': 'blackrock.com',
  'goldman sachs': 'goldmansachs.com',
  'goldman sachs asset management': 'goldmansachs.com',
  'gsam': 'goldmansachs.com',
  'morgan stanley': 'morganstanley.com',
  'morgan stanley investment management': 'morganstanley.com',
  'jp morgan': 'jpmorgan.com',
  'jpmorgan': 'jpmorgan.com',
  'jpmorgan chase': 'jpmorgan.com',
  'j.p. morgan': 'jpmorgan.com',
  'j.p. morgan asset management': 'jpmorgan.com',
  't. rowe price': 'troweprice.com',
  'nuveen': 'nuveen.com',
  'nuveen real estate': 'nuveen.com',
  'fidelity': 'fidelity.com',
  'fidelity investments': 'fidelity.com',
  'fidelity international': 'fidelityinternational.com',
  'vanguard': 'vanguard.com',
  'state street': 'statestreet.com',
  'state street global advisors': 'statestreet.com',
  'invesco': 'invesco.com',
  'franklin templeton': 'franklintempleton.com',
  'pgim': 'pgim.com',
  'houlihan lokey': 'hl.com',
  'lazard': 'lazard.com',
  'lazard asset management': 'lazard.com',
  'partners group': 'partnersgroup.com',
  'hamilton lane': 'hamiltonlane.com',
  'sands capital': 'sandscapital.com',
  'dimensional': 'dimensional.com',
  'ubs': 'ubs.com',
  'ubs asset management': 'ubs.com',
  'ubs group': 'ubs.com',
  'credit suisse': 'credit-suisse.com',
  'deutsche bank': 'db.com',
  'hsbc': 'hsbc.com',
  'hsbc asset management': 'hsbc.com',
  'barclays': 'barclays.com',
  'nomura': 'nomura.com',
  'nomura holdings': 'nomura.com',
  'citigroup': 'citigroup.com',
  'citi': 'citigroup.com',
  'bank of america': 'bankofamerica.com',
  'bofa': 'bankofamerica.com',
  'wells fargo': 'wellsfargo.com',
  'bny mellon': 'bnymellon.com',
  'bny': 'bnymellon.com',
  'bank of new york mellon': 'bnymellon.com',
  'northern trust': 'northerntrust.com',
  'amundi': 'amundi.com',
  'axa': 'axa.com',
  'axa investment managers': 'axa.com',
  'allianz': 'allianz.com',
  'allianz global investors': 'allianz.com',
  'dws': 'dws.com',
  'dws group': 'dws.com',
  'schroders': 'schroders.com',
  'abrdn': 'abrdn.com',
  'aberdeen': 'abrdn.com',
  'm&g': 'mandg.com',
  'm&g investments': 'mandg.com',
  'legal & general': 'legalandgeneral.com',
  'lgim': 'legalandgeneral.com',
  'manulife': 'manulife.com',
  'manulife investment management': 'manulife.com',
  'sun life': 'sunlife.com',
  'macquarie': 'macquarie.com',
  'macquarie group': 'macquarie.com',
  'macquarie asset management': 'macquarie.com',
  'natixis': 'natixis.com',
  'natixis investment managers': 'natixis.com',
  'societe generale': 'societegenerale.com',
  'metlife': 'metlife.com',
  'metlife investment management': 'metlife.com',
  'prudential': 'prudential.com',
  'prudential financial': 'prudential.com',
  'aig': 'aig.com',
  'principal': 'principal.com',
  'principal global investors': 'principal.com',
  'aegon': 'aegon.com',
  'aegon asset management': 'aegon.com',
  'generali': 'generali.com',
  'generali investments': 'generali.com',
  'sei': 'seic.com',
  'sei investments': 'seic.com',
  'wisdomtree': 'wisdomtree.com',
  'janus henderson': 'janushenderson.com',
  'loomis sayles': 'loomissayles.com',
  'mfs': 'mfs.com',
  'mfs investment management': 'mfs.com',
  'capital group': 'capitalgroup.com',
  'wellington': 'wellington.com',
  'wellington management': 'wellington.com',
  'gcm grosvenor': 'gcmgrosvenor.com',

  // ── Secondaries / GP Stakes ─────────────────────────────────────────
  'revelation partners': 'revelation-partners.com',
  'lexington partners': 'lexingtonpartners.com',
  'lexington': 'lexingtonpartners.com',
  'ardian': 'ardian.com',
  'coller capital': 'collercapital.com',
  'coller': 'collercapital.com',
  'neuberger berman': 'nb.com',
  'harbourvest': 'harbourvest.com',
  'harbourvest partners': 'harbourvest.com',
  'adams street': 'adamsstreetpartners.com',
  'adams street partners': 'adamsstreetpartners.com',
  'pantheon': 'pantheon.com',
  'pantheon ventures': 'pantheon.com',
  'stepstone': 'stepstonegroup.com',
  'stepstone group': 'stepstonegroup.com',
  'alpinvest': 'alpinvest.com',
  'alpinvest partners': 'alpinvest.com',
  'pomona capital': 'pomonacapital.com',
  'committed advisors': 'committedadvisors.com',
  'montana capital partners': 'mcp.eu',

  // ── Pensions / Endowments / Sovereigns ──────────────────────────────
  'calpers': 'calpers.ca.gov',
  'calstrs': 'calstrs.com',
  'cppib': 'cppinvestments.com',
  'cpp investments': 'cppinvestments.com',
  'gic': 'gic.com.sg',
  'temasek': 'temasek.com.sg',
  'adia': 'adia.ae',
  'abu dhabi investment authority': 'adia.ae',
  'ontario teachers': 'otpp.com',
  'ontario teachers\' pension plan': 'otpp.com',
  'border to coast': 'bordertocoast.org.uk',
  'cdpq': 'cdpq.com',
  'caisse de depot': 'cdpq.com',
  'omers': 'omers.com',
  'psp investments': 'investpsp.com',
  'psp': 'investpsp.com',
  'bci': 'bci.ca',
  'british columbia investment': 'bci.ca',
  'aimco': 'aimco.ca',
  'alberta investment management': 'aimco.ca',
  'hoopp': 'hoopp.com',
  'pggm': 'pggm.nl',
  'apg': 'apg.nl',
  'apg asset management': 'apg.nl',
  'atp': 'atp.dk',
  'nbim': 'nbim.no',
  'norges bank': 'nbim.no',
  'norges bank investment management': 'nbim.no',
  'kic': 'kic.kr',
  'korea investment corporation': 'kic.kr',
  'pif': 'pif.gov.sa',
  'public investment fund': 'pif.gov.sa',
  'qia': 'qia.qa',
  'qatar investment authority': 'qia.qa',
  'mubadala': 'mubadala.com',
  'mubadala investment company': 'mubadala.com',
  'nz super fund': 'nzsuperfund.nz',
  'new zealand super fund': 'nzsuperfund.nz',
  'future fund': 'futurefund.gov.au',
  'isif': 'isif.ie',
  'ireland strategic investment fund': 'isif.ie',
  'gpif': 'gpif.go.jp',
  'khazanah': 'khazanah.com.my',
  'khazanah nasional': 'khazanah.com.my',
  'texas teachers': 'trs.texas.gov',
  'teacher retirement system of texas': 'trs.texas.gov',
  'florida state board': 'sbafla.com',
  'florida sba': 'sbafla.com',
  'washington state investment board': 'sib.wa.gov',
  'wsib': 'sib.wa.gov',
  'massachusetts prim': 'mapension.com',

  // ── Other notable firms ─────────────────────────────────────────────
  'icg': 'icgam.com',
  'intermediate capital group': 'icgam.com',
  'palladium equity': 'palladiumequity.com',
  'palladium equity partners': 'palladiumequity.com',
  'gryphon investors': 'gryphon-inv.com',
  'gryphon': 'gryphon-inv.com',
  'ik partners': 'ikpartners.com',
  'ik investment partners': 'ikpartners.com',
  'e2p': 'e2pcapital.com',
  'truelink': 'truelinkcapital.com',
  'qhp capital': 'qhpcapital.com',
  'caz investments': 'cazinvestments.com',
  'caz': 'cazinvestments.com',
  'eig': 'eigpartners.com',
  'eig partners': 'eigpartners.com',
  'riverside': 'riversidecompany.com',
  'the riverside company': 'riversidecompany.com',
  'savills': 'savills.com',
  'standard life': 'standardlife.co.uk',
  'infini capital management': 'infinicapital.com',
  'audeo ventures': 'audeoventures.com',
  'swi group': 'swigroup.eu',
  'infravia': 'infraviacapital.com',
  'star mountain capital': 'starmountaincapital.com',
  'galaxy digital': 'galaxydigital.io',
  'carne group': 'carnegroup.com',
  'quilter': 'quilter.com',
  'persistent systems': 'persistent.com',
  'adenia partners': 'adeniapartners.com',

  // ── Credit / Lending / CLO ─────────────────────────────────────────
  'tikehau capital': 'tikehaucapital.com',
  'tikehau': 'tikehaucapital.com',
  'goldentree': 'goldentree.com',
  'goldentree asset management': 'goldentree.com',
  'muzinich': 'muzinich.com',
  'muzinich & co': 'muzinich.com',
  'monroe capital': 'monroecap.com',
  'burford capital': 'burfordcapital.com',
  'burford': 'burfordcapital.com',
  'bonaccord': 'bonaccordcapital.com',
  'bonaccord capital': 'bonaccordcapital.com',
  'pccp': 'pfreim.com',
  'pccp llc': 'pfreim.com',

  // ── European PE / VC ───────────────────────────────────────────────
  'pictet': 'am.pictet',
  'pictet alternative advisors': 'am.pictet',
  'pictet asset management': 'am.pictet',
  'astorg': 'astorg.com',
  'astorg partners': 'astorg.com',
  'alantra': 'alantra.com',
  'ldc': 'ldc.co.uk',
  'credo ventures': 'credoventures.com',
  'ysios capital': 'ysioscapital.com',
  'ysios': 'ysioscapital.com',
  'invenio partners': 'inveniopartners.com',
  'invenio': 'inveniopartners.com',

  // ── Infrastructure ──────────────────────────────────────────────────
  'antin': 'antinfra.com',
  'antin infrastructure partners': 'antinfra.com',
  'global infrastructure partners': 'global-infra.com',
  'gip': 'global-infra.com',
  'stonepeak': 'stonepeak.com',
  'stonepeak partners': 'stonepeak.com',
  'i squared capital': 'isquaredcapital.com',
  'arclight capital': 'arclightcapital.com',
  'arclight': 'arclightcapital.com',
  'copenhagen infrastructure partners': 'cipartners.dk',
  'cip': 'cipartners.dk',
  'actis': 'act.is',
  'meridiam': 'meridiam.com',
  'climate investment': 'climateinvestment.com',

  // ── Real Estate (continued) ───────────────────────────────────────
  'lasalle investment management': 'lasalle.com',
  'lasalle im': 'lasalle.com',
  'lasalle': 'lasalle.com',
  'gladstone management': 'gladstonefunds.com',
  'gladstone': 'gladstonefunds.com',

  // ── Exchanges / Market Infrastructure ──────────────────────────────
  'london stock exchange': 'lseg.com',
  'lseg': 'lseg.com',
  'nasdaq': 'nasdaq.com',
  'nyse': 'nyse.com',
  'ice': 'ice.com',
  'intercontinental exchange': 'ice.com',
  'cme group': 'cmegroup.com',
  'cme': 'cmegroup.com',
  'cboe': 'cboe.com',
  'euronext': 'euronext.com',
  'deutsche boerse': 'deutsche-boerse.com',

  // ── Fund Service Providers ─────────────────────────────────────────
  'citco': 'citco.com',
  'citco group': 'citco.com',
  'ss&c': 'ssctech.com',
  'ss&c technologies': 'ssctech.com',
  'apex group': 'apexgroup.com',
  'apex fund services': 'apexgroup.com',
  'alter domus': 'alterdomus.com',
  'csc': 'cscglobal.com',
  'csc global': 'cscglobal.com',
  'intertrust': 'intertrustgroup.com',
  'intertrust group': 'intertrustgroup.com',
  'vistra': 'vistra.com',
  'vistra group': 'vistra.com',
  'jtc': 'jtcgroup.com',
  'jtc group': 'jtcgroup.com',
  'iq-eq': 'iq-eq.com',
  'ocorian': 'ocorian.com',
  'maples group': 'maples.com',
  'maples': 'maples.com',

  // ── Law Firms ──────────────────────────────────────────────────────
  'kirkland & ellis': 'kirkland.com',
  'kirkland': 'kirkland.com',
  'simpson thacher': 'stblaw.com',
  'simpson thacher & bartlett': 'stblaw.com',
  'latham & watkins': 'lw.com',
  'latham': 'lw.com',
  'sidley austin': 'sidley.com',
  'sidley': 'sidley.com',
  'ropes & gray': 'ropesgray.com',
  'proskauer': 'proskauer.com',
  'proskauer rose': 'proskauer.com',
  'debevoise': 'debevoise.com',
  'debevoise & plimpton': 'debevoise.com',
  'clifford chance': 'cliffordchance.com',
  'freshfields': 'freshfields.com',
  'linklaters': 'linklaters.com',
  'sullivan & cromwell': 'sullcrom.com',
  'davis polk': 'davispolk.com',
  'weil': 'weil.com',
  'weil gotshal': 'weil.com',
  'paul weiss': 'paulweiss.com',
  'skadden': 'skadden.com',
  'skadden arps': 'skadden.com',
  'goodwin': 'goodwinlaw.com',
  'goodwin procter': 'goodwinlaw.com',
  'morgan lewis': 'morganlewis.com',
  'morgan lewis & bockius': 'morganlewis.com',
  'white & case': 'whitecase.com',
  'k&l gates': 'klgates.com',
  'baker mckenzie': 'bakermckenzie.com',
  'allen & overy': 'allenovery.com',
  'a&o shearman': 'aoshearman.com',
  'walkers': 'walkersglobal.com',
  'ogier': 'ogier.com',
  'mourant': 'mourant.com',
  'dechert': 'dechert.com',
  'willkie': 'willkie.com',
  'willkie farr': 'willkie.com',
  'cleary gottlieb': 'clearygottlieb.com',
  'gibson dunn': 'gibsondunn.com',
  'jones day': 'jonesday.com',

  // ── Audit / Accounting ─────────────────────────────────────────────
  'ey': 'ey.com',
  'ernst & young': 'ey.com',
  'deloitte': 'deloitte.com',
  'pwc': 'pwc.com',
  'pricewaterhousecoopers': 'pwc.com',
  'kpmg': 'kpmg.com',
  'rsm': 'rsmus.com',
  'rsm us': 'rsmus.com',
  'grant thornton': 'grantthornton.com',
  'bdo': 'bdo.com',
  'mazars': 'mazars.com',
  'withum': 'withum.com',

  // ── Investment Banks / Advisors ────────────────────────────────────
  'evercore': 'evercore.com',
  'bnp paribas': 'bnpparibas.com',
  'bnp': 'bnpparibas.com',
  'jp morgan chase': 'jpmorgan.com',

  // ── Crypto / Digital Assets ────────────────────────────────────────
  'parafi capital': 'parafi.com',
  'parafi': 'parafi.com',

  // ── Pension Funds / Public Allocators ──────────────────────────────
  'south carolina retirement': 'rsic.sc.gov',
  'south carolina retirement system': 'rsic.sc.gov',
  'illinois municipal retirement': 'imrf.org',
  'illinois municipal retirement fund': 'imrf.org',
  'marin county employees\' retirement': 'mcera.org',
  'marin county employees': 'mcera.org',
  'boston retirement': 'boston.gov',
  'boston retirement system': 'boston.gov',
  'national pension service': 'nps.or.kr',

  // ── Mid-market / Specialty ─────────────────────────────────────────
  'bankinter': 'bankinter.com',
  'elm capital': 'elmcapital.com',
  'forward consumer': 'forwardconsumer.com',
  'midpoint capital partners': 'midpointcp.com',
  'midpoint capital': 'midpointcp.com',
  'first in': 'firstin.vc',
  'broad street development': 'broadstreet.com',
}

/**
 * Map source publication names to their domains for favicon lookup.
 * Used as a final fallback when no firm is identified for an article.
 */
export const SOURCE_DOMAIN_MAP: Record<string, string> = {
  'bloomberg': 'bloomberg.com',
  'bloomberg.com': 'bloomberg.com',
  'bloomberg tax': 'bloomberg.com',
  'bloomberg law': 'bloomberg.com',
  'reuters': 'reuters.com',
  'wsj': 'wsj.com',
  'the wall street journal': 'wsj.com',
  'financial times': 'ft.com',
  'cnbc': 'cnbc.com',
  'business insider': 'businessinsider.com',
  'fortune': 'fortune.com',
  'axios': 'axios.com',
  'techcrunch': 'techcrunch.com',
  'techcrunch vc': 'techcrunch.com',
  'msn': 'msn.com',
  'msn.com': 'msn.com',
  'yahoo finance': 'finance.yahoo.com',

  // Industry publications
  'pensions & investments': 'pionline.com',
  'pitchbook': 'pitchbook.com',
  'pe hub': 'pehub.com',
  'private equity wire': 'privateequitywire.co.uk',
  'private equity international': 'privateequityinternational.com',
  'private equity international | pei': 'privateequityinternational.com',
  'private debt investor': 'privatedebtinvestor.com',
  'alternative credit investor': 'alternativecreditinvestor.com',
  'infrastructure investor': 'infrastructureinvestor.com',
  'secondaries investor': 'secondariesinvestor.com',
  'pere': 'perenews.com',
  'hedge week': 'hedgeweek.com',
  'hedgeweek': 'hedgeweek.com',
  'institutional investor': 'institutionalinvestor.com',
  'investment week': 'investmentweek.co.uk',
  'investmentnews': 'investmentnews.com',
  'altassets': 'altassets.net',
  'altassets private equity news': 'altassets.net',
  'esg today': 'esgtoday.com',
  'agri investor': 'agriinvestor.com',
  'buyouts': 'buyoutsinsider.com',
  'buyouts insider': 'buyoutsinsider.com',
  'venture capital journal': 'venturecapitaljournal.com',
  'alternatives watch': 'alternativeswatch.com',
  'commercial observer': 'commercialobserver.com',

  // News wires
  'pr newswire': 'prnewswire.com',
  'pr newswire financial': 'prnewswire.com',
  'pr newswire - financial services': 'prnewswire.com',
  'business wire': 'businesswire.com',
  'globenewswire': 'globenewswire.com',
  'globenewswire financial services': 'globenewswire.com',

  // Other sources
  'benzinga': 'benzinga.com',
  'thestreet.com': 'thestreet.com',
  'the street': 'thestreet.com',
  'tradingview': 'tradingview.com',
  'hedgeco.net': 'hedgeco.net',
  'pulse 2.0': 'pulse2.com',
  'the recursive': 'therecursive.com',
  'eu-startups.com': 'eu-startups.com',
  'launch base africa': 'launchbaseafrica.com',
  'partnerships bulletin': 'partnershipsbulletin.com',
  'eurasia review': 'eurasiareview.com',
  'everycrsreport.com': 'everycrsreport.com',
  'theglobeandmail.com': 'theglobeandmail.com',
  'the globe and mail': 'theglobeandmail.com',

  // Broadcast / general
  'usa today': 'usatoday.com',
  '24/7 wall street': '247wallst.com',
  '24/7 wall st.': '247wallst.com',
}

/**
 * Look up the domain for a source publication name.
 */
export function getSourceDomain(sourceName: string | null): string | null {
  if (!sourceName) return null
  const key = sourceName.toLowerCase().trim()
  return SOURCE_DOMAIN_MAP[key] ?? null
}

/**
 * Look up the correct domain for a firm name.
 * Tries exact match first, then strips common suffixes (Group, Capital, Partners, etc.).
 * Returns the curated domain if found, otherwise null.
 */
export function getFirmDomain(firmName: string | null): string | null {
  if (!firmName) return null
  const key = firmName.toLowerCase().trim()
  if (FIRM_DOMAIN_MAP[key]) return FIRM_DOMAIN_MAP[key]

  // Try stripping trailing suffixes
  const stripped = key
    .replace(/,?\s*(inc\.?|llc|ltd\.?|l\.?p\.?|plc|corp\.?|co\.?|s\.?a\.?|ag|gmbh|n\.?v\.?|group|partners|management|advisors?)$/i, '')
    .trim()
  if (stripped !== key && FIRM_DOMAIN_MAP[stripped]) return FIRM_DOMAIN_MAP[stripped]

  return null
}
